[build]
builder = "railpack"

[deploy]
startCommand = "flask db upgrade && flask bootstrap-admin && gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
