"""Integração WhatsApp (Z-API): configuração e log de envios.

Cria duas tabelas:

- ``configuracao_zapi``: singleton (id=1) com credenciais Z-API, regras de
  disparo e modelos de mensagem — tudo editável pelo admin no HUD
  (``/integracoes/zapi``). Nasce vazia; a linha é criada sob demanda por
  ``ConfiguracaoZapi.obter()`` (sem backfill aqui, daí sem server_default).
- ``envio_zapi``: log de cada disparo (histórico no HUD + trava
  anti-duplicação do envio agendado). Guarda evento de entrega e contagem do
  instante — nunca o status de férias (esse continua derivado, ver status.py).

Revision ID: 00756c4f6c94
Revises: c7d1a9e4f2b8
Create Date: 2026-06-23 22:51:38.994903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00756c4f6c94'
down_revision = 'c7d1a9e4f2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envio_zapi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('destinatario', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('total_itens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_zapi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('instance_id', sa.String(length=120), nullable=True),
    sa.Column('instance_token', sa.String(length=200), nullable=True),
    sa.Column('client_token', sa.String(length=200), nullable=True),
    sa.Column('destinatarios', sa.Text(), nullable=True),
    sa.Column('notificar_vencida', sa.Boolean(), nullable=False),
    sa.Column('notificar_a_vencer', sa.Boolean(), nullable=False),
    sa.Column('notificar_tem_direito', sa.Boolean(), nullable=False),
    sa.Column('antecedencia_dias', sa.Integer(), nullable=False),
    sa.Column('hora_envio', sa.Integer(), nullable=False),
    sa.Column('apenas_dias_uteis', sa.Boolean(), nullable=False),
    sa.Column('enviar_se_vazio', sa.Boolean(), nullable=False),
    sa.Column('modelo_cabecalho', sa.Text(), nullable=False),
    sa.Column('modelo_linha', sa.Text(), nullable=False),
    sa.Column('modelo_sem_pendencias', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['gestor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_zapi')
    op.drop_table('envio_zapi')
    # ### end Alembic commands ###
