"""schema inicial

Revision ID: 5c39d0288aad
Revises: 
Create Date: 2026-05-27 16:21:38.729460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c39d0288aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('vencto_ferias', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_func_empresa_codigo')
    )
    op.create_table('periodo_aquisitivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=True),
    sa.Column('dias_direito', sa.Float(), nullable=True),
    sa.Column('dias_restantes', sa.Float(), nullable=True),
    sa.Column('limite_gozo', sa.Date(), nullable=True),
    sa.Column('dias_abono', sa.Float(), nullable=True),
    sa.Column('decimo_terceiro', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'inicio', name='uq_periodo_func_inicio')
    )
    op.create_table('programacao_ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('periodo_aquisitivo_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('dias_gozo', sa.Integer(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['periodo_aquisitivo_id'], ['periodo_aquisitivo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'data_inicio', name='uq_prog_func_inicio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programacao_ferias')
    op.drop_table('periodo_aquisitivo')
    op.drop_table('funcionario')
    op.drop_table('setor')
    op.drop_table('empresa')
    # ### end Alembic commands ###
