"""funcionario ativo

Revision ID: 63859db4e304
Revises: a15c6bf0c3a1
Create Date: 2026-06-05 11:19:09.750125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63859db4e304'
down_revision = 'a15c6bf0c3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        # server_default=true() faz backfill das linhas existentes (todas ativas).
        batch_op.add_column(
            sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
