"""gestor e criado_por em programacao

Revision ID: 96b7bbd842a1
Revises: 5c39d0288aad
Create Date: 2026-05-28 23:06:48.462877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b7bbd842a1'
down_revision = '5c39d0288aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('programacao_ferias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_prog_criado_por', 'gestor', ['criado_por_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacao_ferias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prog_criado_por', type_='foreignkey')
        batch_op.drop_column('criado_por_id')

    op.drop_table('gestor')
    # ### end Alembic commands ###
