"""gestor setor_id

Revision ID: a15c6bf0c3a1
Revises: 96b7bbd842a1
Create Date: 2026-06-05 10:51:38.543815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15c6bf0c3a1'
down_revision = '96b7bbd842a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gestor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_gestor_setor', 'setor', ['setor_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gestor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gestor_setor', type_='foreignkey')
        batch_op.drop_column('setor_id')

    # ### end Alembic commands ###
